packages:
  - apps/**
  - packages/**

# v11 default those now.
# https://pnpm.io/blog/releases/11.0#security--build-defaults
#
# blockExoticSubdeps: true
# minimumReleaseAge: 1440

allowBuilds:
  esbuild: false
  lefthook: true
  sharp: false
  workerd: false

catalogs:
  react:
    react: ^19
    react-dom: ^19
    "@types/react": ^19
    "@types/react-dom": ^19
    babel-plugin-react-compiler: ^1.0.0
  tailwindcss:
    tailwindcss: ^4.2
    "@tailwindcss/vite": ^4.2
