packages:
  - apps/**
  # for some reason, Turborepo/pnpm picks this up
  # and refuses to go further /shrug
  - "!apps/**/.output/**"
  - "!apps/**/.nuxt/**"
  - packages/**

# v11 default those now.
# https://pnpm.io/blog/releases/11.0#security--build-defaults
#
# blockExoticSubdeps: true
# minimumReleaseAge: 1440

allowBuilds:
  "@parcel/watcher": false
  esbuild: true
  lefthook: true
  sharp: false
  vue-demi: false
  workerd: false

catalogs:
  oxc:
    oxfmt: 0.48.0
    oxlint: 1.63.0
    oxlint-tsgolint: 0.22.1

  react:
    react: ^19
    react-dom: ^19
    "@types/react": ^19
    "@types/react-dom": ^19
    babel-plugin-react-compiler: ^1.0.0

  tailwindcss:
    tailwindcss: ^4.3
    "@tailwindcss/vite": ^4.3

supportedArchitectures:
  cpu:
    - current
    - x64
  os:
    - current
    - linux
