name: To production, and beyond!
on:
  workflow_dispatch:
  push:
    branches:
      - main

env:
  CLOUDFLARE_ACCOUNT_ID: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
  CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}

jobs:
  sanity-check:
    runs-on: "ubuntu-latest"
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v6
        with:
          node-version: '24'

      - uses: pnpm/action-setup@v6
        name: Install pnpm
        with:
          cache: true

      - name: Install turborepo
        run: |
          pnpm add turbo --global

      - name: Install dependencies
        run: |
          pnpm ci

      - name: Install Playwright browsers
        run: |
          pnpx playwright install --with-deps

      - name: Code quality assurance
        run: |
          turbo quality

      - name: Deploy to Cloudflare Pages
        run: |
          turbo deploy
